name: Build and Sign APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Decode Keystore
        env:
          SIGNING_KEY_STORE_BASE64: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
        run: |
          echo "$SIGNING_KEY_STORE_BASE64" | base64 --decode > ${{ secrets.SIGNING_KEY_STORE_PATH }}

      - name: Build with Gradle
        run: ./gradlew assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}

      - name: List output directory contents
        run: ls -R app/build/outputs/apk/release/

      - name: Upload Unsigned APK
        uses: actions/upload-artifact@v4
        with:
          name: NetGuard-v2.332-release-unsigned.apk
          path: app/build/outputs/apk/release/*
          
      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${{ secrets.SIGNING_KEY_STORE_PATH }} app/build/outputs/apk/release/NetGuard-v2.332-release-unsigned.apk ${{ secrets.SIGNING_KEY_ALIAS }} -storepass ${{ secrets.SIGNING_KEY_PASSWORD }} -keypass ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Verify APK
        run: zipalign -v 4 app/build/outputs/apk/release/NetGuard-v2.332-release-unsigned.apk app-release.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/*
