name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean assembleDebug
      
    - name: Decode Keystore
      env:
        SIGNING_KEY_STORE_BASE64: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
      run: |
        echo "$SIGNING_KEY_STORE_BASE64" | base64 --decode > ${{ secrets.SIGNING_KEY_STORE_PATH }}

    - name: List output directory contents
      run: ls -R app/build/outputs/apk/debug/

    - name: Sign APK
      env:
        SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      run: |
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${{ env.SIGNING_KEY_STORE_PATH }} app/build/outputs/apk/debug/NetGuard-v2.332-debug.apk ${{ env.SIGNING_KEY_ALIAS }} -storepass ${{ env.SIGNING_KEY_PASSWORD }} -keypass ${{ env.SIGNING_KEY_PASSWORD }}

    - name: Verify APK Signature
      run: jarsigner -verify -verbose -certs app/build/outputs/apk/debug/NetGuard-v2.332-debug.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: signed-apk
        path: app/build/outputs/apk/debug/NetGuard-v2.332-debug.apk
